version: "3.8"
services:
  backend:
    image: "ifyang/kau_capstone_onda:develop"
    ports:
      - "80:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "0601"
    depends_on:
      - redis
    restart: "always"
    networks:
      - onda-network

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - onda-network

networks:
  onda-network:
    driver: bridge