spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: prod

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect